@startuml boostan

class Person << entity >> {
    firstName: String
    lastName: String
    ssn: String
}

class Student << entity >> {
    studentID: String
}
Student "*" -- "1" Person
Student "*" -- "1" Major
Student "*" -- "1" Curriculum

class Professor << entity >> {
    employeeID: String
}
Professor "*" -- "1" Person

class Major << entity >> {
    name: String
}
Major "*" -- "1" Degree
Major "1" -- "*" Curriculum

class Degree << entity >> {
    name: String
}

class Curriculum << entity >> {
}
Curriculum "1" -- "*" Semester

class Course << entity >> {
    name: String
}

enum DayOfWeek {
    SAT
    SUN
    MON
    TUE
    WED
    THU
    FRI
}

class Faculty << entity >> {
    name: String
}
Faculty "1" -- "*" Major

class Session << value object >> {
    dayOfWeek: DayOfWeek
    timePeriod: TimePeriod
    place: String
}

class ExamSession << value object >> {
    date: Date
    timePeriod: TimePeriod
    place: String
}

class CourseOffering << entity >> {
    offeredOutside: Boolean
    capacity: Integer
}

CourseOffering "1" -- "0-3" ExamSession
CourseOffering "*" -- "1" Faculty
CourseOffering "1" -- "*" Session
CourseOffering "*" -- "*" Professor
CourseOffering "*" -- "1" Course
CourseOffering "*" -- "1" Semester

class Semester << entity >> {
    registerationPeriod: TimeSpan
    editingPeriod: TimeSpan
    eliminationPeriod: TimeSpan
    year: int
    time: SemesterTime
}

enum SemesterTime {
    FALL,
    SPRING,
    SUMMER    
}

interface CurriculumBoxPassingStrategy {
}

CurriculumBoxPassingStrategy <|.. PassAll
class PassAll {
}

CurriculumBoxPassingStrategy <|.. PassSomeCredits
class PassSomeCredits {
    minCredits: Integer
}

class CurriculumBox {
    passingStrategy: CurriculumBoxPassingStrategy
}

CurriculumBox "*" -- "1" Curriculum
CurriculumRow "*" -- "1" CurriculumBox

abstract class CurriculumRow << value object >> {
    isPassed()
}

CurriculumRow "1" -- "*" Credit

CurriculumRow <|-- SpecificCourse
class SpecificCourse {
}

SpecificCourse "1" -- "1" Course

CurriculumRow <|-- AnyCourse
class AnyCourse {
}

class Credit << value object >> {
    credit: Integer
    type: CreditType
}

enum CreditType {
    THEORY
    PRACTICE
}

abstract class Prerequisite << entity >> {
}

Prerequisite "*" -- "1" Curriculum
Prerequisite "*" -- "1" Course

Prerequisite <|-- CoursePrerequisite
class CoursePrerequisite {
}
CoursePrerequisite "*" -- "1" Course

Prerequisite <|-- CourseCorequisite
class CourseCorequisite {
}

CourseCorequisite "*" -- "1" Course

Prerequisite <|-- MinCreditPrerequisite
class MinCreditPrerequisite {
    minCredit: Integer
}

class Enrollment {
    grade: Integer
    state: EnrollmentState
    verifyGrade()
    finalizeGrade()
    eliminate()
}

enum EnrollmentState {
    PASSED
    FAILED
    GRADE_VERIFIED
    GRADE_NOT_VERIFIED
    NOT_GRADED
    W_ELIMINATED
    X_ELIMINATED
}

Enrollment "*" -- "1" CourseOffering
Enrollment "*" -- "1" CurriculumRow
Enrollment "*" -- "1" StudentSemester

class StudentSemester {
    registerStartTime: Date
    editingStartTime: Date
    submit()
    finalize()
}
StudentSemester "*" -- "1" Semester
StudentSemester "*" -- "1" Student
StudentSemester "1" -- "1" RegistrationValidationStrategy
StudentSemester "1" -- "1" EliminationMinCreditStrategy

class TimePeriod {
    start: Time
    finish: Time
}

class DateTimePeriod {
    start: Date
    finish: Date
}

class SemesterTranscript {
}
SemesterTranscript "1" -- "1" StudentSemester

class Transcript {
}
Transcript "1" -- "1" Student

class EnrollmentPermission {
    type: EnrollmentPermissionType
}
EnrollmentPermission "*" -- "1" CourseOffering
EnrollmentPermission "*" -- "1" StudentSemester

enum EnrollmentPermissionType {
    MINCREDIT
    MAXCREDIT
    REQUISITE
    SESSION_OVERLAP
    OUT_OF_CURRICULUM
    INTERNSHIP_OVERLAP
}

class RegistrationValidationStrategy {
}

RegistrationValidationStrategy <|-- BachelorRegistrationStrategy
class BachelorRegistrationStrategy {
}

RegistrationValidationStrategy <|-- MasterRegistrationStrategy
class MasterRegistrationStrategy {
}

RegistrationValidationStrategy <|-- PhDRegistrationStrategy
class PhDRegistrationStrategy {
}

interface EliminationMinCreditStrategy {
    getMinCredit()
}
EliminationMinCreditStrategy <|-- BachelorEliminationMinCredit
EliminationMinCreditStrategy <|-- BachelorShahedEliminationMinCredit
EliminationMinCreditStrategy <|-- MasterEliminationMinCredit
EliminationMinCreditStrategy <|-- PhDEliminationMinCredit

@enduml